[workspace]
members = [
	"node",
	"pallets/template",
	"pallets/offchain-worker",
	"runtime",
]

[profile.release]
panic = "unwind"
opt-level = 3

[profile.production]
inherits = "release"
lto = true
codegen-units = 1
