[relaychain]
default_image = "parity/polkadot:v0.9.36"
default_command = "polkadot"
chain = "rococo-local"

  [[relaychain.nodes]]
  name = "alice"
  validator = true

  [[relaychain.nodes]]
  name = "bob"
  validator = true

[[parachains]]
id = 1001
chain = "local"
cumulus_based = true

	# run alice as parachain collator
	[[parachains.collators]]
	name = "alice"
	validator = true
  image = "sweatpotato/polkadot-parachain:latest"
  command = "parachain-template-node"
	args = ["-lparachain=debug", "--alice"]