[relaychain]
default_command = "/Users/user/Documents/Develop/repo/polkadot/target/release/polkadot"
chain = "dev"

  [[relaychain.nodes]]
  name = "alice"
  validator = true

  [[relaychain.nodes]]
  name = "bob"
  validator = true

[[parachains]]
id = 1000
chain = "dev"
cumulus_based = true

	# run alice as parachain collator
	[[parachains.collators]]
	name = "alice"
	validator = true
	command = "./target/release/parachain-template-node"
	args = ["-lparachain=debug"]
