[relaychain]
default_command = "/Users/user/Documents/Develop/repo/polkadot/target/release/polkadot"
chain = "rococo-local"

  [[relaychain.nodes]]
  name = "alice"
  validator = true

  [[relaychain.nodes]]
  name = "bob"
  validator = true

[[parachains]]
id = 1000
chain = "statemine-local"
cumulus_based = true

	[[parachains.collators]]
	name = "alice"
	validator = true
	command = "./target/release/polkadot-parachain"
	args = ["-lparachain=debug", "--alice"]

	[[parachains.collators]]
	name = "bob"
	validator = true
	command = "./target/release/polkadot-parachain"
	args = ["-lparachain=debug", "--bob"]

[[parachains]]
id = 1001
chain = "local"
cumulus_based = true

	[[parachains.collators]]
	name = "alice"
	validator = true
	command = "./target/release/parachain-template-node"
	args = ["-lparachain=debug"]